github: [feliciien]
patreon: felicien-diouf
open_collective: workfusion
ko_fi: feliciien
tidelift: npm/workfusion
community_bridge: workfusion
liberapay: felicien-diouf
issuehunt: feliciien
lfx_crowdfunding: workfusion
polar: feliciien
buy_me_a_coffee: feliciien
thanks_dev: feliciien
custom: ['https://github.com/feliciien/SynthAI', 'https://workfusionapp.com/']
